version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/UserDb
      - JWT_SECRET=9151da5571284ccaa7c2b1ad3e0d0657
      - USER=solunkeprithwiraj@gmail.com
      - PASS=xgfjvsfbqswyimrq
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
      
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_configuration:/var/jenkins_configuration
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    container_name: jenkins
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
  jenkins_home: